#!/bin/bash
#
# Run the initdb, then start solr in the foreground
set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

ARGS=

if [[ -z "$EXPORTER_CONFIG" ]]; then
    EXPORTER_CONFIG=/opt/solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml
fi

if [[ ! -z "$EXPORTER_CONFIG" ]]; then
    ARGS="$ARGS -f $EXPORTER_CONFIG"
fi

if [[ ! -z "$EXPORTER_PORT" ]]; then
    ARGS="$ARGS -p $EXPORTER_PORT"
fi

if [[ ! -z "$EXPORTER_SCRAPE_INTERVAL" ]]; then
    ARGS="$ARGS -s $EXPORTER_SCRAPE_INTERVAL"
fi

if [[ ! -z "$EXPORTER_THREADS" ]]; then
    ARGS="$ARGS -n $EXPORTER_THREADS"
fi

if [[ ! -z "$EXPORTER_ZOOKEEPER_CNX" ]]; then
    ARGS="$ARGS -z $EXPORTER_ZOOKEEPER_CNX"
elif [[ ! -z "$EXPORTER_STANDALONE_HOST" ]]; then
    ARGS="$ARGS -b $EXPORTER_STANDALONE_HOST"
else
    echo "EXPORTER_ZOOKEEPER_CNX or EXPORTER_STANDALONE_HOST must be provided to connect to a solr instance, cloud or standalone."
    exit 1
fi

echo "Starting Solr Prometheus Exporter $SOLR_VERSION"

exec /opt/solr/contrib/prometheus-exporter/bin/solr-exporter $ARGS $@
