Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
 config.vm.provision "shell", inline: <<-SHELL
   apt-get update
   apt-get -y install lsof procps curl wget gpg gawk shellcheck vim less git parallel
   apt-get -y install docker.io
   wget -nv --output-document=/usr/local/bin/bashbrew https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/bashbrew-amd64
   chmod a+x /usr/local/bin/bashbrew
   adduser vagrant docker
   echo "vagrant provisioning complete"
 SHELL
end
