#!/bin/bash
# stop the background Solr, and restore the normal configuration

set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

echo "Shutting down the background Solr"
solr stop

echo "Restoring Solr configuration"
mv /opt/solr/bin/solr.in.sh.orig /opt/solr/bin/solr.in.sh
