#!/bin/bash
#
# Start solr prometheus-exporter in the foreground
set -euo pipefail

if [[ "${VERBOSE:-}" = "yes" ]]; then
    set -x
fi

# Make sure the prometheus exporter script exists and can be executed

if [[ -z "${EXPORTER_EXEC:-}" ]]; then
    EXPORTER_EXEC=/opt/solr/contrib/prometheus-exporter/bin/solr-exporter
fi

if [[ ! -f "$EXPORTER_EXEC" ]]; then
    echo "Prometheus Exporter executable \"$EXPORTER_EXEC\" does not exist. Make sure that you are running a compatible solr version (>= 7.3.0)."
    #exit 1
fi

# Set up the command line arguments for the prometheus exporter

ARGS=()

if [[ -n "${EXPORTER_CONFIG:-}" ]]; then
    ARGS+=(-f "$EXPORTER_CONFIG")
fi

if [[ -n "${EXPORTER_PORT:-}" ]]; then
    ARGS+=(-p "$EXPORTER_PORT")
fi

if [[ -n "${EXPORTER_SCRAPE_INTERVAL:-}" ]]; then
    ARGS+=(-s "$EXPORTER_SCRAPE_INTERVAL")
fi

if [[ -n "${EXPORTER_THREADS:-}" ]]; then
    ARGS+=(-n "$EXPORTER_THREADS")
fi

if [[ -n "$EXPORTER_ZOOKEEPER_CNX" ]]; then
    ARGS+=(-z "$EXPORTER_ZOOKEEPER_CNX")
elif [[ -n "$EXPORTER_STANDALONE_HOST" ]]; then
    ARGS+=(-b "$EXPORTER_STANDALONE_HOST")
else
    echo "EXPORTER_ZOOKEEPER_CNX or EXPORTER_STANDALONE_HOST must be provided to connect to a solr instance, cloud or standalone."
    exit 1
fi

echo "Starting Solr Prometheus Exporter: $SOLR_VERSION"
cd /opt/solr/contrib/prometheus-exporter
exec "$EXPORTER_EXEC" "${ARGS[@]}" "${@}"
