#!/bin/bash
#
# Run the initdb, then start solr in the foreground
set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

. /opt/docker-solr/scripts/run-initdb

echo "Starting Solr $SOLR_VERSION"

exec solr -f "$@"
