#!/bin/bash
#
# A helper script to initialise an empty /var/solr

set -e

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

if [ ! -d /var/solr ]; then
    exit
fi

if [ ! -d /var/solr/data ]; then
    mkdir /var/solr/data
fi

if [ ! -d /var/solr/logs ]; then
    mkdir /var/solr/logs
fi

if [ ! -f /var/solr/data/solr.xml ]; then
    cp -a /opt/solr/server/solr/solr.xml /var/solr/data/solr.xml
fi

if [ ! -f /var/solr/data/zoo.cfg ]; then
    cp -a /opt/solr/server/solr/zoo.cfg /var/solr/data/zoo.cfg
fi

if [ ! -f /var/solr/log4j2.xml ]; then
    cp -a ./server/resources/log4j2.xml /var/solr/log4j2.xml
fi

