#!/bin/bash
#
# Create a core on disk and then run solr in the foreground
# arguments are: corename configdir
# To simply create a core:
#      docker run -P -d solr solr-precreate mycore
# To create a core from mounted config:
#      docker run -P -d -v $PWD/myconfig:/myconfig solr solr-precreate mycore /myconfig
# To create a core in a mounted directory:
#      mkdir mycores; chown 8983:8983 mycores
#      docker run -it --rm -P -v $PWD/mycores:/opt/solr/server/solr/mycores solr solr-precreate mycore
# To create multiple cores:
#      docker run -P -d solr solr-precreate mycore1 /path/to/core1 mycore2 /path/to/core2
set -e

echo "Executing $0" "$@"

if [[ "${VERBOSE:-}" = "yes" ]]; then
    set -x
fi

. /opt/docker-solr/scripts/run-initdb

if [ "$#" -eq 0 ]; then
    ARGS="-gettingstarted"
else
    ARGS=$@
fi

while read CORE ARG2; do
    CONFIG_SOURCE=${ARG2:-'/opt/solr/server/solr/configsets/data_driven_schema_configs'}
    if [[ -z $SOLR_HOME ]]; then
        coresdir="/opt/solr/server/solr/mycores"
        mkdir -p $coresdir
    else
        coresdir=$SOLR_HOME
    fi
    coredir="$coresdir/$CORE"
    if [[ ! -d $coredir ]]; then
        cp -r "$CONFIG_SOURCE/" "$coredir"
        touch "$coredir/core.properties"
        echo created "$CORE"
    else
        echo "core $CORE already exists"
    fi
done < <(echo $ARGS | xargs -n2)

exec solr -f
